(() => {
  'use strict';
  const editor=()=>window.PlanEditorAPI;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const key=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const parse=s=>{const d=new Date(`${s}T12:00:00`);return Number.isNaN(d.getTime())?new Date():d};
  const end=e=>e?.endDate&&e.endDate>=e.date?e.endDate:e?.date||'';
  const occurs=(e,d)=>Boolean(e?.date&&e.date<=d&&end(e)>=d);
  const fmt=(d,o={})=>new Intl.DateTimeFormat('ar-SA-u-ca-gregory',o).format(parse(d));
  const visible=e=>window.PlanCalendarV6?.eventVisible?.(e)??true;
  const events=()=>Array.isArray(editor()?.getState?.()?.events)?editor().getState().events:[];
  let view=localStorage.getItem('occ-calendar-view-v3')||'month';
  let selected=localStorage.getItem('occ-calendar-selected-v3')||window.PlanCalendarV6?.getSelectedDate?.()||editor()?.getState?.()?.calendarDate||key(new Date());
  let rendering=false;

  function styles(){if(document.getElementById('occ-calendar-views-style'))return;const s=document.createElement('style');s.id='occ-calendar-views-style';s.textContent=`
  .occ-cal-views{display:flex;gap:4px;padding:3px;border:1px solid var(--gov-line,#dfe4df);border-radius:9px;background:#f5f7f5}.occ-cal-views button{height:30px!important;padding:0 10px!important;border:0!important;background:transparent!important;border-radius:7px!important;color:var(--gov-muted,#66756f)!important}.occ-cal-views button.active{background:var(--gov-accent,#2f6b5c)!important;color:#fff!important}.occ-day-view{height:100%;overflow:auto;padding:13px}.occ-day-head{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:12px;padding:12px;border:1px solid var(--gov-line,#dfe4df);border-radius:12px;background:#f7f9f7}.occ-day-head h3{margin:0;color:var(--gov-ink,#26332f);font-size:18px}.occ-day-head p{margin:3px 0 0;color:var(--gov-muted,#6f7b76);font-size:10px}.occ-day-head button{height:36px;border:0;border-radius:9px;background:var(--gov-accent,#2f6b5c);color:#fff;padding:0 12px;font:900 10px 'Tajawal';cursor:pointer}.occ-day-events{display:grid;gap:8px}.occ-day-event{display:grid;grid-template-columns:7px 1fr auto;gap:10px;align-items:center;border:1px solid var(--gov-line,#dfe4df);border-radius:11px;background:#fff;padding:11px;cursor:pointer}.occ-day-event i{width:7px;height:100%;min-height:42px;border-radius:99px;background:var(--event-color,#2f6b5c)}.occ-day-event strong{display:block;color:var(--gov-ink,#26332f);font-size:12px}.occ-day-event span{display:block;margin-top:3px;color:var(--gov-muted,#6f7b76);font-size:9px}.occ-day-event time{font-size:10px;font-weight:900;color:var(--gov-accent,#2f6b5c)}.occ-year-view{height:100%;overflow:auto;padding:10px;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.occ-year-month{border:1px solid var(--gov-line,#dfe4df);border-radius:12px;background:#fff;padding:9px;min-width:0}.occ-year-month h4{margin:0 0 7px;color:var(--gov-ink,#26332f);font-size:12px}.occ-mini-week,.occ-mini-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:2px;direction:rtl}.occ-mini-week span{font-size:7px;color:var(--gov-muted,#6f7b76);text-align:center}.occ-mini-day{height:25px;border:0;border-radius:6px;background:#f6f8f6;color:#42514b;font:800 8px 'Tajawal';cursor:pointer;position:relative}.occ-mini-day.outside{visibility:hidden}.occ-mini-day.has-events{background:#edf4f0;color:var(--gov-accent,#2f6b5c)}.occ-mini-day.today{outline:2px solid var(--gov-accent,#2f6b5c)}.occ-mini-day b{position:absolute;left:2px;bottom:1px;min-width:11px;height:11px;border-radius:99px;background:var(--gov-accent,#2f6b5c);color:#fff;font-size:6px;display:grid;place-items:center}@media(max-width:1024px){.occ-year-view{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.occ-cal-views{width:100%}.occ-cal-views button{flex:1}.occ-year-view{grid-template-columns:1fr}}
  `;document.head.appendChild(s)}
  function controls(){const c=document.querySelector('.calendarSlide .calendar-controls');if(!c)return;let h=c.querySelector('.occ-cal-views');if(!h){h=document.createElement('div');h.className='occ-cal-views';h.dataset.editorUi='true';h.innerHTML='<button type="button" data-occ-view="month">شهري</button><button type="button" data-occ-view="day">يومي</button><button type="button" data-occ-view="year">سنوي</button>';c.prepend(h)}h.querySelectorAll('[data-occ-view]').forEach(b=>b.classList.toggle('active',b.dataset.occView===view))}
  function setSelected(d){selected=d;localStorage.setItem('occ-calendar-selected-v3',d);const st=editor()?.getState?.();if(st)st.calendarDate=`${d.slice(0,7)}-01`;window.dispatchEvent(new CustomEvent('plan:day-selected',{detail:{date:d}}))}
  function onDay(d){return events().filter(e=>occurs(e,d)&&visible(e)).sort((a,b)=>`${a.time||''}${a.title||''}`.localeCompare(`${b.time||''}${b.title||''}`))}
  function day(main,label){const ev=onDay(selected);label.textContent=fmt(selected,{weekday:'long',day:'numeric',month:'long',year:'numeric'});main.innerHTML=`<div class="occ-day-view"><div class="occ-day-head"><div><h3>${esc(fmt(selected,{weekday:'long',day:'numeric',month:'long'}))}</h3><p>${esc(fmt(selected,{year:'numeric'}))} · ${ev.length} موعد</p></div><button type="button" data-day-add="${esc(selected)}">＋ إضافة موعد</button></div><div class="occ-day-events">${ev.length?ev.map(e=>`<div class="occ-day-event" data-event-id="${esc(e.id)}" style="--event-color:${esc(e.color||'#2f6b5c')}"><i></i><div><strong>${esc(e.title)}</strong><span>${esc(e.notes||'')}${end(e)>e.date?` · حتى ${esc(fmt(end(e),{day:'numeric',month:'short'}))}`:''}</span></div><time>${esc(e.time||'—')}</time></div>`).join(''):'<div class="calendar-empty">لا توجد مواعيد في هذا اليوم.</div>'}</div></div>`}
  function year(main,label){const f=parse(selected),y=f.getFullYear(),today=key(new Date());label.textContent=new Intl.DateTimeFormat('ar-SA-u-ca-gregory',{year:'numeric'}).format(new Date(y,0,1,12));let html='<div class="occ-year-view">';for(let m=0;m<12;m++){const first=new Date(y,m,1,12),start=new Date(first);start.setDate(1-first.getDay());html+=`<section class="occ-year-month"><h4>${esc(new Intl.DateTimeFormat('ar-SA-u-ca-gregory',{month:'long'}).format(first))}</h4><div class="occ-mini-week"><span>ح</span><span>ن</span><span>ث</span><span>ر</span><span>خ</span><span>ج</span><span>س</span></div><div class="occ-mini-grid">`;for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const k=key(d),same=d.getMonth()===m,count=same?onDay(k).length:0;html+=`<button type="button" class="occ-mini-day${same?'':' outside'}${count?' has-events':''}${k===today?' today':''}" data-occ-year-date="${k}" ${same?'':'tabindex="-1"'}>${same?d.getDate():''}${count?`<b>${count}</b>`:''}</button>`}html+='</div></section>'}main.innerHTML=html+'</div>'}
  function alternate(){if(rendering||view==='month')return;const slide=document.querySelector('.calendarSlide'),main=slide?.querySelector('.calendar-main'),label=slide?.querySelector('.calendar-month-label');if(!main||!label)return;rendering=true;try{view==='day'?day(main,label):year(main,label);controls()}finally{rendering=false}}
  function setView(v){view=['month','day','year'].includes(v)?v:'month';localStorage.setItem('occ-calendar-view-v3',view);controls();view==='month'?editor()?.renderCalendar?.():alternate()}
  function shift(n){const d=parse(selected);view==='day'?d.setDate(d.getDate()+n):d.setFullYear(d.getFullYear()+n);setSelected(key(d));alternate();editor()?.saveDataOnly?.()}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-occ-view]');if(b){e.preventDefault();e.stopImmediatePropagation();setView(b.dataset.occView);return}const yd=e.target.closest('[data-occ-year-date]');if(yd){e.preventDefault();e.stopImmediatePropagation();setSelected(yd.dataset.occYearDate);setView('day');return}if(view!=='month'){const a=e.target.closest('[data-cal-action]')?.dataset.calAction;if(['prev','next','today'].includes(a)){e.preventDefault();e.stopImmediatePropagation();if(a==='today'){setSelected(key(new Date()));alternate()}else shift(a==='prev'?-1:1)}}},true);
  window.addEventListener('plan:day-selected',e=>{if(e.detail?.date){selected=e.detail.date;localStorage.setItem('occ-calendar-selected-v3',selected);if(view!=='month')setTimeout(alternate,0)}});
  const init=()=>{styles();controls();const d=document.querySelector('.deck');if(d)new MutationObserver(()=>setTimeout(()=>{controls();if(view!=='month')alternate()},50)).observe(d,{childList:true,subtree:true});setTimeout(()=>{controls();if(view!=='month')alternate()},350)};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
