(() => {
  'use strict';
  const deck=document.querySelector('.deck');if(!deck)return;
  const KEY='page-resource-library';let perm={view:false,edit:false,create:false},seq=0,pending=false,timer=0;
  const session=()=>window.PlanCloudAuth?.getSession?.()||null,slide=()=>deck.querySelector(':scope > .resource-library-slide'),admin=()=>session()?.user?.role==='admin';
  function note(){const s=slide();if(!s)return null;let n=s.querySelector('.resource-access-note');if(!n){n=document.createElement('div');n.className='resource-access-note';n.dataset.editorUi='true';n.style.cssText='display:none;margin:0 0 7px;padding:7px 9px;border:1px solid #dfe4df;border-radius:9px;background:#f7f9f7;color:#5f6e68;font-size:9px;font-weight:900';s.querySelector('.resource-library-toolbar')?.after(n)}return n}
  function message(text='',kind=''){clearTimeout(timer);const n=note();if(!n)return;n.textContent=text;n.style.display=text?'block':'none';n.style.color=kind==='error'?'#934545':kind==='success'?'#2f6b5c':'#5f6e68';if(kind==='success')timer=setTimeout(()=>message(''),3500)}
  function modalToBody(){const m=document.getElementById('resource-modal');if(m&&m.parentElement!==document.body)document.body.appendChild(m);return m}
  function apply(){const s=slide(),a=session();if(!s||!a?.local_token)return;const can=admin()||perm.edit||perm.create;if(admin()||perm.view||can)s.dataset.accessVisible='true';if(can){s.dataset.accessEdit='true';s.dataset.accessCreate='true';document.body.classList.add('cloud-editor');const b=s.querySelector('[data-resource-add]');if(b){b.disabled=false;b.removeAttribute('aria-disabled')}}}
  async function refresh(){const a=session(),token=a?.local_token||'',s=slide(),n=++seq;perm={view:false,edit:false,create:false};if(!s||!token)return false;if(admin()){perm={view:true,edit:true,create:true};apply();return true}try{const access=await window.PlanCloudAuth.rpc('app_get_access',{p_token:token});if(n!==seq||session()?.local_token!==token)return false;const r=(access?.permissions||[]).find(x=>x.page_key===KEY)||{};perm={view:Boolean(r.can_view),edit:Boolean(r.can_edit),create:Boolean(r.can_create)};apply();if(!perm.edit&&!perm.create)message('الحساب الحالي يملك صلاحية عرض المكتبة فقط.');return perm.edit||perm.create}catch(_){message('تعذر التحقق من صلاحية الإضافة.','error');return false}}
  function installRetry(){const api=window.PlanCloudAuth;if(!api?.rpc||api.rpc.__libraryRetry)return;const original=api.rpc.bind(api);const wrapped=async(name,args={},...rest)=>{try{return await original(name,args,...rest)}catch(e){const msg=String(e?.message||e);if(name!=='app_save_section'||!msg.includes('version_conflict')||!args?.p_token||!args?.p_page_key)throw e;const access=await original('app_get_access',{p_token:args.p_token});const latest=(access?.sections||[]).find(r=>r.page_key===args.p_page_key);if(!latest?.version)throw e;const out=await original(name,{...args,p_version:Number(latest.version)},...rest);window.dispatchEvent(new CustomEvent('plan:section-conflict-resolved',{detail:{pageKey:args.p_page_key}}));return out}};wrapped.__libraryRetry=true;api.rpc=wrapped}
  let tries=0;const it=setInterval(()=>{tries++;installRetry();if(window.PlanCloudAuth?.rpc?.__libraryRetry||tries>80)clearInterval(it)},100);installRetry();
  function fallback(){const s=slide(),m=modalToBody(),form=document.getElementById('resource-form');if(!s||!m||!form)return message('تعذر فتح نموذج الإضافة. حدّث الصفحة ثم حاول مرة أخرى.','error');if(!(admin()||perm.edit||perm.create))return message('لا يملك الحساب الحالي صلاحية إضافة موارد.','error');s.dataset.accessEdit='true';s.dataset.accessCreate='true';document.body.classList.add('cloud-editor');form.reset();const id=document.getElementById('resource-id'),title=document.getElementById('resource-modal-title'),msg=document.getElementById('resource-form-message');if(id)id.value='';if(title)title.textContent='إضافة مورد للقادة';if(msg)msg.textContent='';m.classList.add('open');setTimeout(()=>document.getElementById('resource-title')?.focus(),40)}
  document.addEventListener('pointerdown',e=>{const b=e.target.closest('[data-resource-add]');if(b&&slide()?.contains(b)){if(admin()){perm={view:true,edit:true,create:true}}apply()}},true);
  document.addEventListener('click',e=>{const b=e.target.closest('[data-resource-add]');if(!b||!slide()?.contains(b))return;if(admin()){perm={view:true,edit:true,create:true};apply()}setTimeout(()=>{if(!document.getElementById('resource-modal')?.classList.contains('open'))fallback()},0)},true);
  window.addEventListener('plan:local-changed',e=>{if(e.detail?.source==='resource-library'){pending=true;message('جارٍ حفظ المورد ومزامنته…')}});window.addEventListener('plan:sections-saved',e=>{if(!pending)return;pending=false;message(e.detail?.success?'تم حفظ المورد ومزامنته بنجاح.':'تعذر حفظ المورد. البطاقة ما زالت موجودة محليًا.',e.detail?.success?'success':'error')});window.addEventListener('plan:section-conflict-resolved',e=>{if(e.detail?.pageKey===KEY)message('تمت مزامنة النسخة الأحدث وحفظ المورد.','success')});
  new MutationObserver(m=>{if(m.some(x=>x.target===deck&&x.type==='childList'))requestAnimationFrame(()=>{modalToBody();apply()})}).observe(deck,{childList:true});window.addEventListener('plan:session-changed',refresh);window.addEventListener('plan:access-invalidated',refresh);modalToBody();refresh();window.PlanResourceLibraryRepair={refresh,open:fallback};
})();
